<?php
/**
 * LogRelType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Pydio Cells Rest API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

/**
 * LogRelType Class Doc Comment
 *
 * @category    Class
 * @description Relative links types. Note that First is time.Now() and last time.Unix(0). We added an unused NONE enum with value 0 to workaround 0 issues between JSON and proto3.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LogRelType
{
    /**
     * Possible values of this enum
     */
    const NONE = 'NONE';
    const FIRST = 'FIRST';
    const PREV = 'PREV';
    const NEXT = 'NEXT';
    const LAST = 'LAST';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::FIRST,
            self::PREV,
            self::NEXT,
            self::LAST,
        ];
    }
}


